In [1]:
import torch
M=27
N=24
K=12


In [18]:
A=torch.randn(M,K)
B=torch.randn(K,N)
A,B

(tensor([[ 2.7733e-01, -1.5123e-01, -1.2304e+00, -1.2133e+00, -1.7634e+00,
           5.2637e-01, -1.0238e-01,  1.9525e+00,  6.2172e-02, -3.8843e-01,
           1.1864e+00, -8.9849e-01],
         [ 1.5296e+00,  6.9775e-01,  7.0850e-01,  1.4713e+00, -2.3854e-01,
           8.3528e-01,  6.6553e-01,  5.4043e-01, -1.3814e+00,  1.6427e+00,
           7.7671e-01,  8.5083e-01],
         [ 1.8558e-01, -8.2642e-01,  1.5475e+00, -9.5888e-01,  3.4433e-01,
           1.6822e+00,  1.4600e-01,  1.6899e+00,  1.5701e+00, -7.1533e-02,
           8.8669e-01, -2.6985e-01],
         [-8.9661e-01,  1.3808e+00, -9.9195e-01,  5.1477e-01,  2.0502e-02,
          -8.3421e-01, -1.3154e+00,  8.7657e-01,  6.8434e-01,  1.0375e+00,
          -3.6703e-01, -3.8922e-01],
         [ 1.9106e+00,  3.4038e-01, -2.7778e-02,  1.7827e+00, -2.2811e-01,
          -4.6403e-01,  7.6054e-01,  2.0389e+00, -2.5767e+00,  8.2621e-01,
          -9.9550e-01,  1.6045e+00],
         [-6.8568e-01,  2.3905e-01,  1.2484e+00, -3.0732e-01,  9.

In [9]:
M,N,K

(27, 24, 12)

In [10]:
output=torch.zeros(M,N)

In [11]:
block_M = M//3
block_N=N//3
block_K=K//3


In [12]:
block_M,block_N,block_K

(9, 8, 4)

In [21]:
for start_M in range(0,M,block_M):
    stop_M= start_M+block_M

    
    for start_N in range(0,N,block_N):
        stop_N= start_N+block_N
        
        accum=torch.zeros(block_M,block_N)

        for start_K in range(0,K,block_K):
            stop_K=start_K+block_K
            tile_A=A[start_M:stop_M,start_K:stop_K]
            tile_B=B[start_K:stop_K,start_N:stop_N]
            #print("tile A",tile_A)
            #print("tile B",tile_B)
            #print(tile_A.numel())

            accum+=tile_A@tile_B
            #print("accum ",accum)
            

        output[start_M:stop_M,start_N:stop_N]=accum

torch.allclose(output, A@B)


36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36
36


False

In [2]:
x_ptr=torch.randn(1050)
x_ptr

tensor([-0.6842,  1.0767,  2.0093,  ..., -1.2793, -1.1738,  0.5916])

In [3]:
c=torch.arange(0,1024)

In [4]:
c


tensor([   0,    1,    2,  ..., 1021, 1022, 1023])

In [5]:
offset=64+torch.arange(0,1024)
offset

tensor([  64,   65,   66,  ..., 1085, 1086, 1087])

In [6]:
nm=1050

In [7]:
mask=offset<nm
mask

tensor([ True,  True,  True,  ..., False, False, False])

In [8]:
x=x_ptr+offset
x

RuntimeError: The size of tensor a (1050) must match the size of tensor b (1024) at non-singleton dimension 0

In [7]:
import torch

In [2]:
x=torch.randn(4,5)
x

tensor([[ 0.0191, -1.1721, -0.4266,  0.8502,  0.1352],
        [-0.3116, -0.8340, -0.8254,  0.1214,  0.9323],
        [ 0.3426,  0.2967, -0.0836,  0.8714, -0.6098],
        [ 0.2002,  0.1372,  1.3204,  1.6168,  0.4254]])

In [3]:
x_max=x.max(dim=1)[0]

In [4]:
print(x_max)

tensor([0.8502, 0.9323, 0.8714, 1.6168])


In [7]:
print(x_max.shape)
x_max_1=x.max(dim=0)
print(x_max_1)

torch.Size([4])
torch.return_types.max(
values=tensor([0.3426, 0.2967, 1.3204, 1.6168, 0.9323]),
indices=tensor([2, 2, 3, 3, 1]))


In [10]:
r=x-x_max[:,None]
print(r)

tensor([[-0.8311, -2.0223, -1.2767,  0.0000, -0.7150],
        [-1.2439, -1.7663, -1.7577, -0.8110,  0.0000],
        [-0.5289, -0.5747, -0.9551,  0.0000, -1.4812],
        [-1.4166, -1.4797, -0.2965,  0.0000, -1.1914]])


In [11]:
print(x_max[:,None])

tensor([[0.8502],
        [0.9323],
        [0.8714],
        [1.6168]])


In [12]:
print(x_max[None,:])

tensor([[0.8502, 0.9323, 0.8714, 1.6168]])


In [13]:
numerator=torch.exp(r)
print(numerator)

tensor([[0.4356, 0.1324, 0.2789, 1.0000, 0.4892],
        [0.2883, 0.1710, 0.1724, 0.4444, 1.0000],
        [0.5893, 0.5629, 0.3848, 1.0000, 0.2274],
        [0.2425, 0.2277, 0.7434, 1.0000, 0.3038]])


In [18]:
denominator=numerator.sum(dim=1)
print(denominator)

tensor([2.3361, 2.0761, 2.7643, 2.5175])


In [21]:
print("numerator shape",numerator.shape)
print("denomianator shape",denominator.shape)
result=numerator/denominator[:,None]

print(result)

numerator shape torch.Size([4, 5])
denomianator shape torch.Size([4])
tensor([[0.1865, 0.0567, 0.1194, 0.4281, 0.2094],
        [0.1388, 0.0823, 0.0831, 0.2141, 0.4817],
        [0.2132, 0.2036, 0.1392, 0.3618, 0.0822],
        [0.0963, 0.0905, 0.2953, 0.3972, 0.1207]])


In [23]:
row_sum=result.sum(dim=1)
print(row_sum)

tensor([1.0000, 1.0000, 1.0000, 1.0000])


In [28]:
y=torch.empty_like(x)
print(y,y.shape)

tensor([[6.6074e+04, 1.6381e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]) torch.Size([4, 5])


In [6]:
print_order = ["the","cat","is","on","a","chair"]
sequence = [{print_order[i]} for i in range(len(print_order))]
sequence

[{'the'}, {'cat'}, {'is'}, {'on'}, {'a'}, {'chair'}]

In [ ]:
sliding_window_size=3

def sliding_window_attention(seq:list[set[str]],w:int):
    seq_len=len(seq)
    print("the length of sequence of type 'list[set[str]] is ",seq_len)
    attention_scores: list[list[set]] = [[None for _ in range(seq_len)] for _ in range(seq_len)]
    for i , q_i in enumerate(seq):
        for j , q_j in enumerate(seq):

            if j>i:
                continue

            if j-i>=w:
                continue

            attention=set()
            attention.update(q_i)
            attention.update(q_j)
            attention_scores[i][j]=attention


In [24]:
M,N,K = 27,27,8
BLOCK_SIZE_M , BLOCK_SIZE_N , BLOCK_SIZE_K = 3,3,2




In [19]:
A=torch.randn(M,K)
B=torch.randn(K,N)
A,B

(tensor([[-2.3947e+00, -2.2940e-01,  2.1989e-01, -2.5202e-01,  8.1194e-01,
          -2.6301e-01, -2.4291e-01, -2.8600e-01],
         [ 1.4727e-01,  5.0780e-01,  8.0161e-01, -4.9933e-01,  1.5565e+00,
          -3.2561e-01, -7.6039e-01, -2.5790e-01],
         [ 3.3600e-01,  6.6345e-01, -2.4063e-01,  2.3834e-01,  6.5702e-01,
          -1.1029e+00, -1.8345e+00,  1.4962e+00],
         [ 2.9292e-01, -4.6175e-02,  7.2082e-01,  8.1139e-01, -5.6472e-01,
          -1.0001e+00, -9.5001e-01, -3.6828e-01],
         [ 9.7238e-01,  1.2278e+00,  2.2260e-01,  2.6480e-01, -6.8892e-01,
          -7.0919e-01,  1.0436e+00,  6.1702e-01],
         [-3.4161e-01, -9.1487e-01, -3.9451e-01,  6.8422e-01, -2.1132e+00,
          -7.9409e-01,  1.3459e-01,  7.0443e-01],
         [-2.6722e-01, -3.8839e-02,  1.4961e+00, -1.3221e+00, -2.9251e-01,
           1.1699e+00,  1.6335e+00, -6.0037e-01],
         [-1.5281e+00, -6.4492e-01,  3.5592e-01, -5.4961e-01, -2.4111e-01,
           5.6049e-01,  5.6883e-01, -2.3266e-02],


In [25]:
for m in range(0, M, BLOCK_SIZE_M):
  # Do in parallel
  for n in range(0, N, BLOCK_SIZE_N):
    acc = torch.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=torch.float32)
    C=torch.zeros(BLOCKSIZE_M,BLOCKSIZE_N)
    for k in range(0, K, BLOCK_SIZE_K):
      a = A[m : m+BLOCK_SIZE_M, k : k+BLOCK_SIZE_K]
      b = B[k : k+BLOCK_SIZE_K, n : n+BLOCK_SIZE_N]
      acc += (a @ b)
    C[m : m+BLOCK_SIZE_M, n : n+BLOCK_SIZE_N] = acc

RuntimeError: The expanded size of the tensor (2) must match the existing size (3) at non-singleton dimension 1.  Target sizes: [2, 2].  Tensor sizes: [3, 3]